# Generated by Django 3.2.10 on 2021-12-20 11:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clases', '0007_solution'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.IntegerField()),
                ('solution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mark', to='clases.solution')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mark', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
